apiVersion: v1
kind: Service
metadata:
  name: node-hostname-service
  namespace: nodehostname
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: node-hostname
