apiVersion: v1
kind: Service
metadata:
  name: node-hostname-service
  namespace: {{ .Values.appname }}
  labels:
    {{- include "node-hostname.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "node-hostname.labels" . | nindent 4 }}
