replicaCount: 2

image:
  repository: node-hostname
  tag: v3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

appname: nodehostname

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

readinessProbe:
  path: "/"
  initialDelaySeconds: 5
  periodSeconds: 10
